[[questions]]
id = "30212501-00d5-4ef6-838f-3df5112ee7ed"
type = "Tracing"
prompt.program = """
fn main() {
  let message = "The temperature today is:";
  let x = [message, 100];
  println!("{} {}", x[0], x[1]);
}
"""
answer.doesCompile = false
answer.lineNumber = 3
context = """
An array can only contain elements of a single type. The syntax `[message, 100]` creates an array with two elements.
The variable `message` is a string, and the constant `100` is a number.
"""

[[questions]]
id = "4e632a23-24cc-4c29-8935-cf6b62c3764b"
type = "Tracing"
prompt.program = """
fn main() {
  let t = ([1; 2], [3; 4]);
  let (a, b) = t;
  println!("{}", a[0] + t.1[0]); 
}
"""
answer.doesCompile = true
answer.stdout = "4"
context = """
The syntax `[x; y]` declares an array with `y` copies of the value `x`. The syntax `(a, b)` destructures `t` and binds `a` to `[1; 2]`. 
The syntax `t.1` refers to the second element of `t`, which is `[3; 4]`.
"""