[[questions]]
id = "f4971d37-55d5-48c5-9966-a28b54ed3bee"
type = "Tracing"
prompt.program = """
use std::ops::Deref;

#[derive(Clone, Copy)]
struct AccessLogger(i32);

impl Deref for AccessLogger {
    type Target = i32;
    fn deref(&self) -> &Self::Target {
        println!("deref");
        &self.0
    }
}

fn main() {
  let n = AccessLogger(-1);
  let x = *n + 1;
  let n2 = n;
  println!("{} {}", x, *n)
}
"""
answer.doesCompile = true
answer.stdout = """
deref
deref
0 -1
"""
context = """
The `AccessLogger` will print "deref" every time `n` is dereferenced, which occurs twice.
Note that copying `n` to `n2` does not dereference `n`.
"""